#!/bin/sh
set -eu

export PGPASSWORD="$POSTGRES_PASSWORD"
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-SQL
  CREATE ROLE ${METABASE_BI_USER} LOGIN PASSWORD '${METABASE_BI_PASSWORD}';
  CREATE ROLE ${METABASE_APP_USER} LOGIN PASSWORD '${METABASE_APP_PASSWORD}';
  GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${METABASE_BI_USER};
  GRANT USAGE ON SCHEMA public TO ${METABASE_BI_USER};
SQL
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<-SQL
  CREATE DATABASE ${METABASE_APP_DB:-metabase} OWNER ${METABASE_APP_USER};
SQL
